from enum import Enum


class EffectType(Enum):

    ACTIVATE_TRIGGER = 8
    # TODO add all from eEffect

eEffect = {
    0: "Invalid Effect",
    1: "Change Diplomacy",
    2: "Research Technology",
    3: "Send Chat",
    4: "Play Sound",
    5: "Send Tribute",
    6: "Unlock Gate",
    7: "Lock Gate",
    8: "Activate Trigger",
    9: "Deactivate Trigger",
    10: "AI Script Goal",
    11: "Create Object",
    12: "Task Object",
    13: "Declare Victory",
    14: "Kill Object",
    15: "Remove Object",
    16: "Change View",
    17: "Unload",
    18: "Change Ownership",
    19: "Patrol",
    20: "Display Instructions",
    21: "Clear Instructions",
    22: "Freeze Unit",
    23: "Use Advanced Buttons",
    24: "Damage Object",
    25: "Place Foundation",
    26: "Change Object Name",
    27: "Change Object HP",
    28: "Change Object Attack",
    29: "Stop Object",
    30: "Attack Move",
    31: "Change Object Armor",
    32: "Change Object Range",
    33: "Change Object Speed",
    34: "Heal Object",
    35: "Teleport Object",
    36: "Change Object Stance",
    37: "Display Timer",
    38: "Enable/Disable Object",
    39: "Enable/Disable Technology",
    40: "Change Object Cost",
    41: "Set Player Visibility",
    42: "Change Object Icon",
    43: "Replace Object",
    44: "Change Object Description",
    45: "Change Player Name",
    46: "Change Train Location",
    47: "Change Research Location",
    48: "Change Civilization Name",
    49: "Create Garrisoned Object",
    50: "Acknowledge AI Signal",
    51: "Modify Attribute",
    52: "Modify Resources",
    53: "Modify Resources By Variable",
    54: "Modify Research Cost",
    55: "Modify Research Time",
    56: "Change Variable",
    57: "Clear Timer",
    58: "Effect 1"
}
